gg_theme = Theme(
    backgroundcolor = bg,
    Figure = (backgroundcolor = bg,),
    Scene = (backgroundcolor = bg,),
    Axis = (
        titlealign = :left,
        xgridvisible   = true,
        ygridvisible   = true,
        ygridcolor   = (:grey,0.3),
        xgridcolor   = (:grey,0.3),
        xgridwidth   = 2,
        ygridwidth   = 2,
        spinewidth = 4,
        rightspinecolor = :grey,
        leftspinecolor = :grey,
        topspinecolor = :grey,
        bottomspinecolor = :grey,
        xlabelsize = 26,
        titlefont = fig_font,
        titlesize = 26,
        xticklabelfont = fig_font,
        xticklabelsize = 20,
        yticklabelfont = fig_font,
        ylabelfont = fig_font,
        xlabelfont = fig_font,
        ylabelsize = 26,
        yticklabelsize = 20,
        backgroundcolor= bg
    ),
    Axis3 = (
        titlealign = :left,
        xgridvisible   = false,
        ygridvisible   = false,
        xlabelsize = 26,
        titlefont = fig_font,
        titlesize = 26,
        xticklabelfont = fig_font,
        xticklabelsize = 20,
        yticklabelfont = fig_font,
        zticklabelfont = fig_font,
        ylabelfont = fig_font,
        xlabelfont = fig_font,
        zlabelfont = fig_font,
        zlabelsize = 26,
        backgroundcolor= bg
    ),
    Legend = (
    backgroundcolor = bg,
      titlefont = fig_font,
      labelfont = fig_font,
      labelsize = 20,
      titlesize = 20,
    ),
    Colorbar = (
      titlefont = fig_font,
      labelfont = fig_font,
      labelsize = 20,
      titlesize = 20,
    )
)
